# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20161028_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
