# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_auto_20161028_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='content',
            new_name='message',
        ),
    ]
